env:
    browser: false
    es6: true
    node: true
    mocha: true
parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
plugins:
    - '@typescript-eslint'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended'
rules:
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    '@typescript-eslint/no-explicit-any':
        - error
    '@typescript-eslint/interface-name-prefix':
        - error
        - always

